version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - VITE_API_URL=http://localhost:3000/api
        - VITE_WS_URL=ws://localhost:3000
        - VITE_ENV=development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - bidingo-network
    command: npm run dev

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ../backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/bidingo_dev
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev_secret
      - CORS_ORIGIN=http://localhost:5173
    networks:
      - bidingo-network
    depends_on:
      - mongodb
      - redis
    command: npm run dev

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - bidingo-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bidingo-network

volumes:
  mongodb_data:
  redis_data:

networks:
  bidingo-network:
    driver: bridge